<a href="https://colab.research.google.com/github/pcriwtshah/Data-Science-Pre-requisites/blob/main/Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basic matrix operation using numpy: \

add() − add elements of two matrices.

subtract() − subtract elements of two matrices.

divide() − divide elements of two matrices; This is not matrix division

multiply() − multiply elements of two matrices.

dot() − It performs matrix multiplication, not element wise multiplication; notice difference between multiply and dot

sqrt() − square root of each element of matrix.

sum(x,axis) − add to all the elements in matrix. Second argument is optional, it is used when we want to compute the column sum if axis is 0 and row sum if axis is 1.

“T” − It performs transpose of the specified matrix.


In [1]:
import numpy as np

In [10]:
A = [[1, 2], [3, 4]]
A

[[1, 2], [3, 4]]

In [11]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [14]:
B = np.array([[5, 6], [7, 8]])
B

array([[5, 6],
       [7, 8]])

In [13]:
add_matrix = np.add(A, B)
add_matrix

array([[ 6,  8],
       [10, 12]])

In [16]:
sub_matrix1 = np.subtract(A, B)
sub_matrix1

array([[-4, -4],
       [-4, -4]])

In [17]:
sub_matrix2 = np.subtract(B, A)
sub_matrix2

array([[4, 4],
       [4, 4]])

In [18]:
sub_matrix3 = np.subtract(B, B)
sub_matrix3

array([[0, 0],
       [0, 0]])

In [21]:
mul_matrix1 = np.multiply(A, B)
mul_matrix1

array([[ 5, 12],
       [21, 32]])

In [22]:
C = np.array([[1, 2, 3], [4, 5, 6]])
C

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
mul_matrix2 = np.multiply(A, C)
mul_matrix2

ValueError: ignored

In [25]:
np.shape(A), np.shape(B), np.shape(C)

((2, 2), (2, 2), (2, 3))